### ISSUE TITLE
Continuous integration has not been set up 

### ISSUE THREAD

**Issue by alexeymaslov** [alexeymaslov/js-playground#15]
GitHub Actions and several other apps can be used to automatically catch bugs and enforce style. =)

**Comment by Axroy** [comment]
@alexeymaslov 
[This action](https://github.com/marketplace/actions/deploy-to-heroku) seems to be a good choice for deployment. Unfortunately, I am unable to do setup due to the fact that I don't have access to the repo settings and the Heroku API key.

**Comment by Axroy** [comment]
Other kinds of CI are still being investigated 🔍 .

**Comment by alexeymaslov** [comment]
> 
> 
> @alexeymaslov
> [This action](https://github.com/marketplace/actions/deploy-to-heroku) seems to be a good choice for deployment. Unfortunately, I am unable to do setup due to the fact that I don't have access to the repo settings and the Heroku API key.

1. Have just added HEROKU_API_KEY secret to the repo. It do be linked to my heroku account though. 
2. Also added you as a collaborator to heroku approximately a week ago; check if you can manage the app on heroku.

**Comment by alexeymaslov** [comment]
> 
> 
> Other kinds of CI are still being investigated 🔍 .

I think something similar to https://github.com/marketplace/actions/tslint-checks would be cool.
